In [60]:
import pandas as pd 
import numpy as np 
import kagglehub

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.datasets import load_iris
import seaborn as sns
import matplotlib.pyplot as plt

In [61]:
# Cargar el dataset Iris
iris = load_iris(as_frame = True)
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [62]:
dfIris = iris.frame

In [63]:
dfIris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

## Exploración de conjunto de datos

In [64]:
dfIris.shape

(150, 5)

In [65]:
dfIris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [66]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [67]:
dfIris.rename(columns= { "target": "especia" } , inplace = True)

In [68]:
dfIris["especia"] = dfIris["especia"].map({
    0 : "setosa",
    1 : "versicolor",
    2: "virginica",
})

In [69]:
dfIris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),especia
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [70]:
dfIris.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),especia
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

## Identificar variables predictoras y variables objetivo

In [71]:
# Variable predictoria 
X = dfIris.drop(columns=["especia"]) 
print ("Variables predictoras")
print (X.columns)

Variables predictoras
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [72]:
# Variable objetivo 
y = dfIris["especia"]
print ("Variables objetivo")
print (y.name)

Variables objetivo
especia

## Dividir los datos en la prueba y entrenamiento

**80%** para entrenamiento
**20%** para prueba

In [73]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.20,
    random_state = 42
)

In [74]:
print ("X_train: ", X_train.shape)
print ("X_test: ", X_test.shape) 
print ("y_train: ", y_train.shape) 
print ("y_test: ", y_test.shape)

X_train:  (120, 4)
X_test:  (30, 4)
y_train:  (120,)
y_test:  (30,)

## Escalado de variables

In [75]:
scaler = StandardScaler()

In [76]:
## Escalamos las variables
scaler = StandardScaler()
X_train_escalado = scaler.fit_transform(X_train)
X_test_escalado = scaler.transform(X_test)

In [77]:
print("Sin escalar")
print(X_train)
print("Escalado")
print(X_train_escalado)

Sin escalar
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                 4.6               3.6                1.0               0.2
15                 5.7               4.4                1.5               0.4
65                 6.7               3.1                4.4               1.4
11                 4.8               3.4                1.6               0.2
42                 4.4               3.2                1.3               0.2
..                 ...               ...                ...               ...
71                 6.1               2.8                4.0               1.3
106                4.9               2.5                4.5               1.7
14                 5.8               4.0                1.2               0.2
92                 5.8               2.6                4.0               1.2
102                7.1               3.0                5.9               2.1

[120 rows x 4 columns]
Escalado
[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]
 [-1.23014297  0.75647855 -1.2187007  -1.31260282]
 [-1.7177306   0.30929911 -1.39061772 -1.31260282]
 [ 0.59831066 -1.25582892  0.72969227  0.95664273]
 [ 0.72020757  0.30929911  0.44316389  0.4227026 ]
 [-0.74255534  0.98006827 -1.27600637 -1.31260282]
 [-0.98634915  1.20365799 -1.33331205 -1.31260282]
 [-0.74255534  2.32160658 -1.27600637 -1.44608785]
 [-0.01117388 -0.80864948  0.78699794  0.95664273]
 [ 0.23261993  0.75647855  0.44316389  0.55618763]
 [ 1.08589829  0.08570939  0.55777524  0.4227026 ]
 [-0.49876152  1.87442714 -1.39061772 -1.04563275]
 [-0.49876152  1.4272477  -1.27600637 -1.31260282]
 [-0.37686461 -1.47941864 -0.01528151 -0.24472256]
 [ 0.59831066 -0.58505976  0.78699794  0.4227026 ]
 [ 0.72020757  0.08570939  1.01622064  0.8231577 ]
 [ 0.96400139 -0.13788033  0.38585821  0.28921757]
 [ 1.69538284  1.20365799  1.3600547   1.75755292]
 [-0.13307079 -0.36147005  0.27124686  0.15573254]
 [ 2.18297047 -0.13788033  1.64658307  1.22361279]
 [-0.2549677  -0.13788033  0.44316389  0.4227026 ]
 [-0.86445224  0.98006827 -1.33331205 -1.31260282]
 [ 2.30486738 -0.58505976  1.70388875  1.09012776]
 [-0.01117388 -0.80864948  0.21394119 -0.24472256]
 [-0.74255534  0.75647855 -1.33331205 -1.31260282]
 [-0.98634915  0.98006827 -1.39061772 -1.17911778]
 [-0.86445224  1.65083742 -1.04678367 -1.04563275]
 [-0.98634915 -2.37377751 -0.12989286 -0.24472256]
 [ 0.59831066 -0.80864948  0.67238659  0.8231577 ]
 [-1.23014297  0.75647855 -1.04678367 -1.31260282]
 [-0.98634915 -0.13788033 -1.2187007  -1.31260282]
 [-0.86445224  0.53288883 -1.16139502 -0.91214772]
 [-0.2549677  -0.80864948  0.27124686  0.15573254]
 [-0.86445224  0.75647855 -1.27600637 -1.31260282]
 [-0.13307079 -0.13788033  0.27124686  0.02224751]
 [ 2.30486738  1.65083742  1.70388875  1.35709783]
 [-1.47393679  0.30929911 -1.33331205 -1.31260282]
 [ 0.47641375 -0.36147005  0.32855254  0.15573254]
 [-0.13307079 -1.25582892  0.72969227  1.09012776]
 [-0.37686461  2.5451963  -1.33331205 -1.31260282]
 [ 0.23261993 -0.13788033  0.61508092  0.8231577 ]
 [-0.01117388 -0.80864948  0.78699794  0.95664273]
 [ 0.23261993 -1.92659808  0.15663551 -0.24472256]
 [-0.49876152 -0.13788033  0.44316389  0.4227026 ]
 [ 0.47641375  0.75647855  0.95891497  1.49058286]
 [-0.37686461 -1.70300836  0.15663551  0.15573254]
 [-0.49876152  1.87442714 -1.16139502 -1.04563275]
 [-0.98634915 -1.70300836 -0.24450422 -0.24472256]
 [ 0.72020757 -0.80864948  0.90160929  0.95664273]
 [-0.98634915  0.53288883 -1.33331205 -1.31260282]
 [-0.98634915  0.30929911 -1.4479234  -1.31260282]
 [-0.37686461 -1.47941864  0.04202416 -0.11123753]
 [ 1.08589829 -0.13788033  0.72969227  0.68967267]
 [-1.10824606  0.08570939 -1.27600637 -1.31260282]
 [-0.01117388 -0.58505976  0.78699794  1.62406789]
 [-0.98634915  0.75647855 -1.27600637 -1.31260282]
 [-0.98634915  0.98006827 -1.2187007  -0.77866269]
 [ 0.11072303  0.30929911  0.61508092  0.8231577 ]
 [-0.86445224 -1.25582892 -0.41642124 -0.11123753]
 [ 1.32969211  0.30929911  1.130832    1.49058286]
 [ 0.23261993 -0.80864948  0.78699794  0.55618763]
 [ 0.35451684 -1.0322392   1.07352632  0.28921757]
 [ 2.30486738 -0.13788033  1.3600547   1.49058286]
 [-0.37686461 -1.25582892  0.15663551  0.15573254]
 [-1.7177306  -0.36147005 -1.33331205 -1.31260282]
 [-1.83962751 -0.13788033 -1.50522907 -1.44608785]
 [ 0.23261993 -1.92659808  0.72969227  0.4227026 ]
 [ 1.69538284  0.30929911  1.30274902  0.8231577 ]
 [-1.47393679  0.08570939 -1.27600637 -1.31260282]
 [-0.86445224  0.98006827 -1.33331205 -1.17911778]
 [-1.7177306  -0.13788033 -1.39061772 -1.31260282]
 [ 0.59831066 -1.25582892  0.67238659  0.4227026 ]
 [ 0.59831066  0.75647855  1.07352632  1.62406789]
 [-1.47393679  0.75647855 -1.33331205 -1.17911778]
 [ 1.2077952  -0.13788033  1.01622064  1.22361279]
 [ 0.59831066  0.53288883  1.30274902  1.75755292]
 [-1.35203988  0.30929911 -1.39061772 -1.31260282]
 [ 0.35451684 -0.36147005  0.55777524  0.28921757]
 [ 0.84210448 -0.58505976  0.50046957  0.4227026 ]
 [ 0.47641375 -0.58505976  0.61508092  0.8231577 ]
 [ 1.45158902  0.30929911  0.55777524  0.28921757]
 [ 0.72020757  0.30929911  0.90160929  1.49058286]
 [-0.86445224  1.65083742 -1.2187007  -1.31260282]
 [ 1.32969211  0.08570939  0.95891497  1.22361279]
 [ 0.11072303 -0.13788033  0.27124686  0.4227026 ]
 [ 0.84210448 -0.13788033  0.84430362  1.09012776]
 [-0.13307079 -1.0322392  -0.12989286 -0.24472256]
 [-0.74255534 -0.80864948  0.09932984  0.28921757]
 [ 0.35451684 -0.13788033  0.50046957  0.28921757]
 [-1.5958337  -1.70300836 -1.39061772 -1.17911778]
 [ 0.96400139 -0.36147005  0.50046957  0.15573254]
 [-0.37686461 -1.0322392   0.38585821  0.02224751]
 [-0.62065843  1.4272477  -1.27600637 -1.31260282]
 [-0.2549677  -0.13788033  0.21394119  0.15573254]
 [ 1.81727975 -0.36147005  1.47466605  0.8231577 ]
 [ 1.08589829  0.53288883  1.130832    1.22361279]
 [-0.86445224  1.4272477  -1.27600637 -1.04563275]
 [-1.10824606 -1.47941864 -0.24450422 -0.24472256]
 [ 1.08589829  0.53288883  1.130832    1.75755292]
 [ 1.69538284 -0.13788033  1.18813767  0.55618763]
 [-1.10824606  1.20365799 -1.33331205 -1.44608785]
 [ 1.08589829  0.08570939  1.07352632  1.62406789]
 [-1.10824606 -0.13788033 -1.33331205 -1.31260282]
 [ 1.32969211  0.08570939  0.67238659  0.4227026 ]
 [ 1.93917666 -0.58505976  1.3600547   0.95664273]
 [ 0.59831066 -0.36147005  1.07352632  0.8231577 ]
 [-0.13307079 -0.58505976  0.21394119  0.15573254]
 [ 0.84210448 -0.13788033  1.01622064  0.8231577 ]
 [ 0.59831066 -1.70300836  0.38585821  0.15573254]
 [ 0.72020757 -0.36147005  0.32855254  0.15573254]
 [-0.2549677  -0.58505976  0.67238659  1.09012776]
 [ 0.11072303 -0.13788033  0.78699794  0.8231577 ]
 [-0.49876152  0.75647855 -1.16139502 -1.31260282]
 [ 0.35451684 -0.58505976  0.15663551  0.15573254]
 [-1.10824606 -1.25582892  0.44316389  0.68967267]
 [-0.01117388  2.09801686 -1.4479234  -1.31260282]
 [-0.01117388 -1.0322392   0.15663551  0.02224751]
 [ 1.57348593 -0.13788033  1.24544335  1.22361279]]

## Entrenamiento del modelo KNN
En esta prueba utilizaremos k = 3

In [78]:
modelo = KNeighborsClassifier(n_neighbors= 3)
modelo.fit(
    X_train_escalado, y_train
)

KNeighborsClassifier(n_neighbors=3)

## Realizamos predicciones con variables de prueba

In [79]:
prediccion = modelo.predict(X_test_escalado)
print(prediccion[:10])

['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor']

In [80]:
## Comparacion entre valores reales y valores predecidos
comparacion = pd.DataFrame({
    "especie rear": y_test.values,
    "especie predicha": prediccion
})
comparacion.head(30)

   especie rear especie predicha
0    versicolor       versicolor
1        setosa           setosa
2     virginica        virginica
3    versicolor       versicolor
4    versicolor       versicolor
5        setosa           setosa
6    versicolor       versicolor
7     virginica        virginica
8    versicolor       versicolor
9    versicolor       versicolor
10    virginica        virginica
11       setosa           setosa
12       setosa           setosa
13       setosa           setosa
14       setosa           setosa
15   versicolor       versicolor
16    virginica        virginica
17   versicolor       versicolor
18   versicolor       versicolor
19    virginica        virginica
20       setosa           setosa
21    virginica        virginica
22       setosa           setosa
23    virginica        virginica
24    virginica        virginica
25    virginica        virginica
26    virginica        virginica
27    virginica        virginica
28       setosa           setosa
29       setosa           setosa

In [81]:
## Evaluacion del modelo

In [82]:
accuracy = accuracy_score(
    y_test,
    prediccion
)
print(f"Accuracy/exactitud : {accuracy: 4f}")

Accuracy/exactitud :  1.000000

In [83]:
## Matriz de confusion
cm = confusion_matrix(y_test, prediccion)
cm_df = pd.DataFrame(cm, index = modelo.classes_,columns = modelo.classes_)
cm_df

            setosa  versicolor  virginica
setosa          10           0          0
versicolor       0           9          0
virginica        0           0         11

## Clasification report
proporciona metricas que permiten evaluar el desempeño de cada. clase: precision, recall,f1-score, suport

In [84]:
print(classification_report(y_test, prediccion))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30