<a href="https://colab.research.google.com/github/tenchipe23/extraccion_de_conocimientos_de_DB/blob/main/primera_practica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [11]:
import json
import random
from datetime import datetime, timedelta

def generar_datos(cantidad):
    nombres = ["Juan", "María", "Pedro", "Ana", "Carlos", "Laura", "Diego", "Sofía", "Miguel", "Lucía"]
    ciudades = ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancun", "Merida", "Tijuana", "Yucatan"]
    categoria = ["Tegnologia", "Ropa", "Hogar", "Videojuegos", "Deportes", ]
    usuarios = []

    # Fecha base para el cálculo de fecha_registro
    fecha_inicio = datetime(2020, 1, 1)

    print(f"Generando {cantidad} registros... Por favor, espera.")

    for i in range(cantidad):
        # Creamos cada objeto individual
        registro = {
            "usuario": random.choice(nombres),
            "edad": random.randint(18, 80),
            "ciudad": random.choice(ciudades),
            "compras_realizadas": random.randint(0, 50),
            "activo": random.choice([True, False]),
            "categoria": random.choice(categoria),
            "fecha_registro": (fecha_inicio + timedelta(days=random.randint(0, 1500))).strftime("%Y-%m-%d")
        }
        usuarios.append(registro)

        # Opcional: imprimir progreso cada 250,000 registros
        if (i + 1) % 250000 == 0:
            print(f"Progreso: {i + 1} registros creados.")

    return usuarios

def guardar_en_json(datos, DataFrame):
    print(f"Escribiendo datos en {DataFrame}...")
    with open(DataFrame, 'w', encoding='utf-8') as f:
        json.dump(datos, f, ensure_ascii=False, indent=4)
    print("¡Archivo generado con éxito!")

# --- Ejecución ---
NUM_REGISTROS = 1000000
ARCHIVO = "datos_usuarios.json"

datos_generados = generar_datos(NUM_REGISTROS)
guardar_en_json(datos_generados, ARCHIVO)

Generando 1000000 registros... Por favor, espera.
Progreso: 250000 registros creados.
Progreso: 500000 registros creados.
Progreso: 750000 registros creados.
Progreso: 1000000 registros creados.
Escribiendo datos en datos_usuarios.json...
¡Archivo generado con éxito!

In [6]:
df = pd.read_json("datos_usuarios.json");
print(df)

       usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0         Juan    39       Cancun                  38   False     2024-01-06
1        María    62       Merida                   0   False     2021-02-21
2          Ana    57       Merida                  50    True     2020-08-17
3       Miguel    20    Monterrey                  33   False     2023-06-19
4        Sofía    32    Monterrey                  44    True     2022-05-05
...        ...   ...          ...                 ...     ...            ...
999995   Pedro    49      Yucatan                  11    True     2021-11-18
999996    Juan    30         CDMX                   5   False     2021-05-24
999997   Lucía    34      Yucatan                  19    True     2023-12-11
999998  Carlos    59       Puebla                  18   False     2024-02-06
999999   Diego    40  Guadalajara                  21   False     2023-01-17

[1000000 rows x 6 columns]

In [12]:
df.shape

(1000000, 6)

In [13]:
df.dtypes

usuario               object
edad                   int64
ciudad                object
compras_realizadas     int64
activo                  bool
fecha_registro        object
dtype: object

In [10]:
df.memory_usage(deep=True)

Index                      132
usuario               58699496
edad                   8000000
ciudad                55997592
compras_realizadas     8000000
activo                 1000000
fecha_registro        59000000
dtype: int64